### ISSUE TITLE
add spread({ source, target })

### ISSUE THREAD

**Issue by sergeysova** [sergeysova/patronum#4]
Just full variant with object argument

**Comment by doasync** [comment]
Not just full variant, the whole signature should be changed:

```js
// BROKEN
spread({ target1, target2 })

// OK
spread(source, {
 target1, target2
})

// GOOD
const target = spread({
 source,
 target: {target1, target2}
})
```

Here is an example why it should return target shape and why this signature should be removed spread({ target1, target2 }):

```js
const {
  age,
  name,
} = spread({
 source: updateUserData,
 target: restore(
   name: '',
   age: 0
 )
})
```

**Comment by doasync** [comment]
If you want to use it with `sample` just put sample in the source:

```js
spread({
  source: sample(...),
  target: {}
})
```

**Comment by doasync** [comment]
Don't change current behavior, please!

**Comment by sergeysova** [comment]
@doasync What the decision?

**Comment by doasync** [comment]
There are still discussions... Maybe it should be used as a separate step (with source + targets) and not return source at all (it may be confusing for some users). I admit that it's convenient for using as a target in sample, but not sure if it's a good practice. Maybe it should be integrated into `sample` as a part of its functionality.

Let's just leave its current implementation untouched! There are not enough arguments (nor any requests from community) to change its signature for config instead of targets... and the worst part is, it's a breaking change. From a practical standpoint, the current one is better.

**Comment by sergeysova** [comment]
@doasync But current implementation will change in #49. Maybe add support for `{ source, target }` ?

**Comment by doasync** [comment]
@sergeysova I think you should deprecate `spread(targets)` signature first, and/or introduce this change in major version

**Comment by doasync** [comment]
`spread(source, targets)` can cover all needs for now

**Comment by sergeysova** [comment]
@doasync We can deprecate it in `0.14.x` branch and `latest` npm-tag.

But in `master` branch, `0.100+` version, and `next` npm version release it without previous form.
